title: design-project-template
hero_image: images/banner.png
description: design-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Define your window
  - title: Make a scrolling backdrop
  - title: Draw objects that move around
  - title: Add a player sprite
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
