title: Don't collide!
hero_image: images/banner.png
description: Build an obstacle game where your character has to reach a finishing point without colliding.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Choose your theme
  - title: Create obstacles
  - title: Obstacle scrolling
  - title: Collision detection
  - title: Win the game
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
